### ISSUE TITLE
Erorr Message when installing outlook-matters

### ISSUE THREAD

**Issue by rayguilliard** [makmu/outlook-matters#60]
Hello,
i get the following error message. This is in german but maybe someone can help me?

![2016-06-10 18_24_31-issues makmu_outlook-matters - internet explorer](https://cloud.githubusercontent.com/assets/19860490/15971292/b20c5268-2f38-11e6-814a-6f300cb4d829.png)

**Comment by rayguilliard** [comment]
![2016-06-10 18_29_47-visual studio tools for office solution installer](https://cloud.githubusercontent.com/assets/19860490/15971489/96a805fc-2f39-11e6-81da-3810908cdf81.png) / English version

**Comment by makmu** [comment]
Hi rayguilliard,

There seems to be a [bug](http://support.dataeverywhere.com/article/48-error-the-value-of-the-property-type-cannot-be-parsed) in the Microsoft Visual Studio Tools for Office Runtime. Could you please try to move `VSTOInstaller.exe.config` in
`C:\Program Files (x86)\Common Files\Microsoft Shared\VSTO\10.0`
or
`C:\Program Files\Common Files\Microsoft Shared\VSTO\10.0`
away be renaming it to to `VSTOInstaller.exe.config.old` as suggested in this [article](http://support.dataeverywhere.com/article/48-error-the-value-of-the-property-type-cannot-be-parsed) and try to install the addin again?

**Comment by rayguilliard** [comment]
thanks makmu !! ... now it works. But now I get the following error... 

``Name: OutlookMatters
From: file:///C:/Program Files/Outlookmatters/OutlookMatters.vsto

************** Exception Text **************
System.Security.SecurityException: Customized functionality in this application will not work because the certificate used to sign the deployment manifest for OutlookMatters or its location is not trusted. Contact your administrator for further assistance.
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustPromptKeyInternal(ClickOnceTrustPromptKeyValue promptKeyValue, DeploymentSignatureInformation signatureInformation, String productName, TrustStatus status)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustUsingPromptKey(Uri manifest, DeploymentSignatureInformation signatureInformation, String productName, TrustStatus status)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.ProcessSHA2Manifest(ActivationContext context, DeploymentSignatureInformation signatureInformation, PermissionSet permissionsRequested, Uri manifest, ManifestSignatureInformationCollection signatures, AddInInstallationStatus installState, TrustStatus sha256TrustStatus, X509Certificate2 sha256PublisherCert)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.VerifySecurity(ActivationContext context, Uri manifest, AddInInstallationStatus installState)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()
The Zone of the assembly that failed was:
MyComputer

Maybe this is a Admin-Problem on my side. ? It's a Company-Laptop.

**Comment by totofa** [comment]
Hi,
I've got the problem with 1.3.0 with my Company-Laptop.

**Comment by maxmueller89** [comment]
I have the same problem with my laptop. It's a Windows 10 Pro with AD. Anyone has an idea?
