### ISSUE TITLE
Trust Issue - revived

### ISSUE THREAD

**Issue by chrber** [makmu/outlook-matters#63]
This question has popped up twice now ( #54 and #60 ) and both times there was no answer concerning the trust certificate issues. I guess you have used a selfsigned certificate to sign the AddIn. 

Does that mean we can not trust this AddIn?

Please respond to this standing issue.

Thanks you.

**Comment by chrber** [comment]
In the properties of the vsto file one can change the trust of the file but then one gets

Name: 
From: file:///C:/Users/bernardt/AppData/Local/Temp/Temp1_outlook-matters-1.3.0.zip/OutlookMatters.vsto

************** Exception Text **************
System.Deployment.Application.InvalidDeploymentException: Deployment and application do not have matching security zones.
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

**Comment by Zether** [comment]
To get rid of the "Deployment and application do not have matching security zones" error you need unblock all the files you unpacked one by one (in the right click -> properties dialog). Not only the .vsto file. After that it will be installed correctly.
