### ISSUE TITLE
'Microsoft Visual Studio Tools for Office Runtime 2010' still needed for building from source?

### ISSUE THREAD

**Issue by makmu** [makmu/outlook-matters#7]
We should check whether 'Microsoft Visual Studio Tools for Office Runtime 2010' are still needed for building from source and if not adjust the documentation accordingly

**Comment by makmu** [comment]
A test installation of Windows 10 and Visual Studio 2015 from scratch showed that 'Microsoft Visual Studio Tools for Office Runtime 2010' **is necessary** for building. Without, Visual Studio shows the following error message when building:

```
Error		The "RegisterFormRegions" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Tools.Office.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Tools.Office.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.VisualStudio.Tools.Office.BuildTasks.RegisterFormRegions.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].	OutlookMatters		
```

So, all is well. We don't need to update the documentation.
